### ISSUE TITLE
Module build failed: Error: Cannot remove "babel-plugin-transform-es2015-modules-commonjs" from the plugin list.

### ISSUE THREAD

**Issue by ubergarm** [vuejs-templates/webpack-simple-2.0#12]
Just got this error may be related to this: https://github.com/gajus/babel-preset-es2015-webpack/issues/10

Steps to repeat:

    docker run --rm -it -v `pwd`:/app mhart/alpine-node /bin/sh
    cd /app
    apk --no-cache add git
    npm install -g vue-cli
    vue init webpack-simple-2.0 my_app
    cd my_app
    npm install
    npm run dev

Thanks

**Comment by alexsinfarosa** [comment]
I've got the same error.

**Comment by djgadd** [comment]
Just following some of the issues above, I've managed to work around it: -

`npm install --save-dev babel-preset-es2015`

and updated my .babelrc file to: -

`{
  "presets": [
    [
      "es2015",
      {
        "modules": false
      }
    ]
  ]
}
`

It's late here, and I just want to do some playful hacking so in all honesty I haven't read much in those tickets, I just lucked into a solution, ymmv but that was on a fresh install.

Hope it helps.

**Comment by yyx990803** [comment]
Updated to use `preset-es2015` with `{ modules: false }`.
