### ISSUE TITLE
Should ES6 module handling be delegated to Webpack 2?

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs-templates/webpack-simple-2.0#15]
It [looks like](https://gist.github.com/sokra/27b24881210b56bbaff7#es6-modules). I'd just make the change, but would like a sanity check first to make sure there aren't ramifications I'm not considering.

**Comment by yyx990803** [comment]
It already is: https://github.com/vuejs-templates/webpack-simple-2.0/blob/master/template/.babelrc#L3
