### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by chovy** [vuejs-templates/webpack-simple-2.0#17]
when I run `npm run build` it puts a .js and a .png file in `./dist` but no index.html.

seems incomplete.

**Comment by jamesxv7** [comment]
@chovy I understand that is the expected location. I just run the template using vue-cli and works very nice.

**Comment by chrisvfritz** [comment]
@jamesxv7 is right - there's no need to move the `index.html` file in this template. The project root is simply the public root.
