### ISSUE TITLE
Eslint instead of Jshint

### ISSUE THREAD

**Issue by sunabozu** [vuejs-templates/webpack-simple-2.0#20]
Hi.

Many people nowadays use eslint instead of jshint. Would be nice to have it in this template, maybe as an option.

**Comment by chrisvfritz** [comment]
We'd like the keep the "simple" templates relatively simple, but ESLint is included in the full Webpack template, which also has a [2.0 branch](https://github.com/vuejs-templates/webpack/tree/2.0).
