### ISSUE TITLE
Syntax Question webpack-simple-2.0 

### ISSUE THREAD

**Issue by nueverest** [vuejs-templates/webpack-simple-2.0#21]
In index.html I see `<div id="app"></div>` as opposed to `<div id="app"><app></app></div>`

Also in App.vue I see another `<div id="app">`.  At first glance, I intuited that when I use developer tools on index.html in the browser I would see something like:

```
<div id="app">
    <div id="app">
        <img src="/dist/logo.png?82b9c7a5a3f405032b1db71a25f67021"> 
        <h1>Hello Vue 2.0!</h1>
    </div>
</div>
```

However, when I use developer tools I see only one div with an id of "app". Vue is doing more than I expected in this case.  

Is this pattern considered a best practice?

**Comment by crswll** [comment]
When you use a component Vue essentially replaces the node you're mounting it on. If you change the `<div id="app">...</div>` in `./src/App.vue` you'll see that.

**Comment by nueverest** [comment]
Right is there some rationale or documentation behind this behavior. It was not intuitive for me.

**Comment by crswll** [comment]
There's a `replace` option that you can set to `false` that would result with what you would expect.

```
<div id="app">
  <div id="app">
    ...
  </div> 
</div>
```

http://vuejs.org/api/#replace

This option going away in 2.0 though. It's best to just get used to the replace behavior.

**Comment by chrisvfritz** [comment]
Yes, it's a best practice. 😃  The rationale is that every Vue instance already has a root element, so there's no point in having two. The same end result can easily be achieved by giving the root element the same id as the one you're mounting to, as is done in the template, thus making `replace: false` redundant.
