### ISSUE TITLE
Cannot Get Basic Init to Run (Fresh Windows 10, Node 4.4.7, Npm 2.15.8, vue-cli 2.1.1)

### ISSUE THREAD

**Issue by xioustic** [vuejs-templates/webpack-simple-2.0#4]
As of 2016-07-28:
Step 1: Install latest Node LTS
Step 2: npm install vue-cli -g
Step 3: vue init webpack-simple-2.0 test
Step 4: cd test
Step 5: npm install
Step 6: npm run dev
Step 7: browse to localhost:8080
Step 8: nothing appears on page; error in console:
  vue.common.js?e881:2244[Vue warn]: Failed to mount component: template or render function not defined. (found in anonymous component - use the "name" option for better debugging messages.))

Don't know enough about Vue 2.0 and Webpack to fix this or figure it out; very frustrating that the most basic hot-module boilerplate for 2.0 won't even work on a fresh machine with standard Node LTS install. I must be missing something very basic?

**Comment by dotneet** [comment]
I created two PRs(#6,#7) a little while ago.
These PRs solve this problem.

**Comment by xioustic** [comment]
Thanks!
